services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Macpaw\SymfonyMessengerBundle\Middleware\:
    resource: '../src/Middleware/*'

  Macpaw\SymfonyMessengerBundle\Middleware\AddSyncCommandStampMiddleware:
    arguments:
      $sendersLocator: '@messenger.senders_locator'
